---

-  name: Create Consul node
   shell: >
     docker-machine create
     --driver amazonec2
     --amazonec2-zone {{ AWS_ZONE }}
     --amazonec2-region {{ EC2_REGION }}
     --amazonec2-access-key {{ AWS_ACCESS_KEY }}
     --amazonec2-secret-key {{ AWS_SECRET_KEY }}
     --amazonec2-vpc-id {{ AWS_VPC_ID }}
     --amazonec2-security-group docker-networking 
     sw-consul

-  name: Start Consul Container on node
   shell: > 
     docker $(docker-machine config sw-consul) run -d
     -p "8500:8500"
     -h "consul"
     progrium/consul -server -bootstrap

-  name: Add public key to Consul node
   shell: cat ~/.ssh/authorized_keys | docker-machine ssh sw-consul 'umask 077; cat >>.ssh/authorized_keys' 