---

-  name: Install Docker
   shell: wget -qO- https://get.docker.com/ | sh

-  name: Install Docker-Machine
   shell: curl -L https://github.com/docker/machine/releases/download/v0.3.0/docker-machine_linux-amd64 > /usr/local/bin/docker-machine

-  name: Change permission on file
   file: path=/usr/local/bin/docker-machine mode=0100

-  name: Install Docker-Compose
   shell: curl -L https://github.com/docker/compose/releases/download/1.3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

-  name: Change permission on file
   file: path=/usr/local/bin/docker-compose mode=0100

-  name: Create Swarm Token
   shell: echo $(docker run swarm create)
   register: SWARM_TOKEN

-  name: Create Swarm Master
   shell: docker-machine --debug create --driver amazonec2 --amazonec2-zone {{ AWS_ZONE }} --amazonec2-region {{ AWS_DEFAULT_REGION }} --amazonec2-access-key {{ AWS_ACCESS_KEY_ID }} --amazonec2-secret-key {{ AWS_SECRET_ACCESS_KEY }} --amazonec2-vpc-id {{ AWS_VPC_ID }}  --swarm --swarm-master --swarm-discovery token://{{ SWARM_TOKEN.stdout }} swarm-master

-  name: Create Swarm Nodes
   shell: docker-machine --debug create --driver amazonec2 --amazonec2-zone {{ AWS_ZONE }} --amazonec2-region {{ AWS_DEFAULT_REGION }} --amazonec2-access-key {{ AWS_ACCESS_KEY_ID }} --amazonec2-secret-key {{ AWS_SECRET_ACCESS_KEY }} --amazonec2-vpc-id {{ AWS_VPC_ID }}  --swarm --swarm-discovery token://{{ SWARM_TOKEN.stdout }} swarm-node-{{ item }}
   with_sequence: count={{ NODE_COUNT }}
