---

-  name: Create Swarm Token
   shell: echo $(docker run swarm create)
   register: SWARM_TOKEN

-  name: Create Swarm Master
   shell: >
     docker-machine create
     --driver amazonec2
     --amazonec2-zone {{ AWS_ZONE }}
     --amazonec2-region {{ EC2_REGION }}
     --amazonec2-access-key {{ AWS_ACCESS_KEY }}
     --amazonec2-secret-key {{ AWS_SECRET_KEY }}
     --amazonec2-vpc-id {{ AWS_VPC_ID }}
     --amazonec2-security-group docker-networking 
     --swarm
     --swarm-master
     --swarm-discovery consul://$(docker-machine ip sw-consul):8500
     --engine-opt="cluster-store=consul://$(docker-machine ip sw-consul):8500"
     --engine-opt="cluster-advertise=eth0:0"
     swarm-master

-  name: Create Swarm Nodes
   shell: >
     docker-machine create
     --driver amazonec2
     --amazonec2-zone {{ AWS_ZONE }}
     --amazonec2-region {{ EC2_REGION }}
     --amazonec2-access-key {{ AWS_ACCESS_KEY }}
     --amazonec2-secret-key {{ AWS_SECRET_KEY }}
     --amazonec2-vpc-id {{ AWS_VPC_ID }}
     --amazonec2-security-group docker-networking 
     --swarm
     --swarm-discovery consul://$(docker-machine ip sw-consul):8500
     --engine-opt="cluster-store=consul://$(docker-machine ip sw-consul):8500"
     --engine-opt="cluster-advertise=eth0:0"
     swarm-node-{{ item }}
   with_sequence: count={{ NODE_COUNT }}

-  name: Add public key to Swarm Master
   shell: cat ~/.ssh/authorized_keys | docker-machine ssh swarm-master 'umask 077; cat >>.ssh/authorized_keys'

-  name: Add public key to Swarm Nodes
   shell: cat ~/.ssh/authorized_keys | docker-machine ssh swarm-node-{{ item }} 'umask 077; cat >>.ssh/authorized_keys'
   with_sequence: count={{ NODE_COUNT }}
