---

-  name: Create Swarm Token
   shell: echo $(docker run swarm create)
   register: SWARM_TOKEN
   tags:
     - swarm

-  name: Create Swarm Master
   shell: docker-machine --debug create --driver amazonec2 --amazonec2-zone {{ AWS_ZONE }} --amazonec2-region {{ EC2_REGION }} --amazonec2-access-key {{ AWS_ACCESS_KEY }} --amazonec2-secret-key {{ AWS_SECRET_KEY }} --amazonec2-vpc-id {{ AWS_VPC_ID }}  --swarm --swarm-master --swarm-discovery token://{{ SWARM_TOKEN.stdout }} swarm-master
   tags:
     - swarm

-  name: Create Swarm Nodes
   shell: docker-machine --debug create --driver amazonec2 --amazonec2-zone {{ AWS_ZONE }} --amazonec2-region {{ EC2_REGION }} --amazonec2-access-key {{ AWS_ACCESS_KEY }} --amazonec2-secret-key {{ AWS_SECRET_KEY }} --amazonec2-vpc-id {{ AWS_VPC_ID }}  --swarm --swarm-discovery token://{{ SWARM_TOKEN.stdout }} swarm-node-{{ item }}
   with_sequence: count={{ NODE_COUNT }}
   tags:
     - swarm

-  name: Add public key to Swarm Master
   shell: cat ~/.ssh/authorized_keys | docker-machine ssh swarm-master 'umask 077; cat >>.ssh/authorized_keys'
   tags:
     - public_key

-  name: Add public key to Swarm Nodes
   shell: cat ~/.ssh/authorized_keys | docker-machine ssh swarm-node-{{ item }} 'umask 077; cat >>.ssh/authorized_keys'
   with_sequence: count={{ NODE_COUNT }}
   tags:
     - public_key
