---

-  name: Install apt_key for Docker repo
   apt_key: keyserver=hkp://pgp.mit.edu:80 id=58118E89F3A912897C070ADBF76221572C52609D
   become: yes
   become_method: sudo   

-  name: Add source to docker.list file
   lineinfile: dest=/etc/apt/sources.list.d/docker.list create=yes line="deb https://apt.dockerproject.org/repo ubuntu-trusty main"
   become: yes
   become_method: sudo     

-  name: Install Docker
   apt: update_cache=yes name=docker-engine
   become: yes
   become_method: sudo     

-  name: Change permissions on /usr/local/bin
   shell: sudo chown -R $(whoami) /usr/local/bin

-  name: Install Docker-Machine
   get_url: url=https://github.com/docker/machine/releases/download/v0.3.0/docker-machine_linux-amd64 dest=/usr/local/bin/docker-machine 

-  name: Install Docker-Compose
   shell: curl -L https://github.com/docker/compose/releases/download/1.3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

-  name: Change permission on docker binaries
   file: path=/usr/local/bin/{{ item }} mode=0555
   with_items: 
     - docker-machine
     - docker-compose