---

-  name: Install zip
   apt: name=zip state=present
   become: yes
   become_method: sudo

-  name: Install apt_key for Docker repo
   apt_key: keyserver=hkp://pgp.mit.edu:80 id=58118E89F3A912897C070ADBF76221572C52609D
   become: yes
   become_method: sudo   

-  name: Add source to docker.list file
   lineinfile: dest=/etc/apt/sources.list.d/docker.list create=yes line="deb https://apt.dockerproject.org/repo ubuntu-trusty main"
   become: yes
   become_method: sudo     

-  name: Install Docker Engine Latest
   apt: update_cache=yes name=docker-engine
   become: yes
   become_method: sudo     

-  name: Change permissions on /usr/local/bin
   shell: sudo chown -R $(whoami) /usr/local/bin

-  name: Install Docker-Machine v0.5.0
   get_url: url=https://github.com/docker/machine/releases/download/v0.5.0/docker-machine_linux-amd64.zip dest=/usr/local/bin

-  name: Unzip Docker-Machine binary
   unarchive: src=/usr/local/bin/docker-machine_linux-amd64.zip dest=/usr/local/bin copy=no  

-  name: Remove Docker-Machine zip file
   file: path=/usr/local/bin/docker-machine_linux-amd64.zip state=absent

-  name: Install Docker-Compose v1.5.0
   get_url: url=https://github.com/docker/compose/releases/download/1.5.0/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose

-  name: Change permission on docker binaries
   file: path=/usr/local/bin/{{ item }} mode=0555
   with_items: 
     - docker-machine
     - docker-compose
